// Package executor is the builder loop's dispatch boundary (DESIGN.md §2, §9).
//
// Apex does not implement the builder loop. It assembles context and a task
// brief, then hands both to an external coding agent running in the project
// directory: Apex owns the judgment, the agent owns the edits. Everything in
// this package is about that handover — what a brief carries, what a run
// reports back, and what "this executor can actually run here" means.
//
// The interface exists so a native builder loop can drop in later with no
// other change (DESIGN.md §17). It is deliberately smaller than the provider
// interface: one call, one stream of typed events, no structured output.
//
// Nothing here writes to the database or reads config. The command layer owns
// the exec_runs row, the per-project lock, and the status transitions; this
// package owns one subprocess.
package executor

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/RazerBlade6/apex/internal/provider"
)

// TaskBrief is one unit of dispatched work.
//
// Instruction carries *intent* — what to do, why it matters, how to know it is
// done — and never project background. That is not a token-saving measure: the
// agent runs with cmd.Dir set to ProjectPath, so PROJECT.md and any CLAUDE.md
// are already in its working tree (DESIGN.md §6, §9). Restating them in the
// brief would spend tokens to tell the agent something it can read, and would
// go stale the moment the user edited the file.
//
// RunID, SessionID and LogPath are additions to the struct in DESIGN.md §9.
// The spec requires all three to exist — the run id correlates the lock, the
// exec_runs row and the log file (§10); the session id is generated by Apex
// and stored so a stalled run is resumable with `claude --resume` (§9); the
// log lives at ~/.apex/logs/exec/<run-id>.log (§5) — and this struct is where
// a dispatch says which ones it is using. An executor that does not resume or
// log ignores them.
type TaskBrief struct {
	// RunID correlates this dispatch across the lock file, the exec_runs row
	// and the log.
	RunID string
	// SessionID is the agent session identifier Apex generated. Empty lets
	// the executor decide, which forfeits resumability.
	SessionID string
	// ActionItemID is the item being implemented, or empty for work that has
	// no item behind it — scaffolding a new project from an idea.
	ActionItemID string
	// ProjectPath is the working directory for the dispatched agent.
	ProjectPath string
	// Title is one line naming the task.
	Title string
	// Instruction is the assembled brief. See the note above on intent.
	Instruction string
	// ContextPaths names files the agent should read first, relative to
	// ProjectPath. It is a pointer, not a payload: the files are in the
	// working tree and the agent reads them itself.
	ContextPaths []string
	// LogPath is where the run's output is teed. Empty disables logging.
	LogPath string
}

// Validate reports a brief that cannot be dispatched.
func (b TaskBrief) Validate() error {
	if strings.TrimSpace(b.ProjectPath) == "" {
		return fmt.Errorf("executor: the brief names no project directory to work in")
	}
	if strings.TrimSpace(b.Instruction) == "" {
		return fmt.Errorf("executor: the brief carries no instruction")
	}
	return nil
}

// EventType tags an Event.
//
// DESIGN.md §9 sketches three values — output, done, error. The extra two are
// there because the same section requires the stream to be parsed rather than
// scraped: "the executor can distinguish tool calls from file edits from the
// final result and map them onto typed Event values". Three types could not
// carry that distinction, so it would have been thrown away at the boundary
// the spec asked to preserve it at.
type EventType int

const (
	// EventOutput is assistant text: what the agent is saying as it works.
	EventOutput EventType = iota
	// EventToolUse is the agent calling a tool that does not change a file —
	// reading, searching, running a command.
	EventToolUse
	// EventFileEdit is the agent writing to a file. Path names it. This is
	// the event a user actually wants to watch, which is why it is not
	// folded into EventToolUse.
	EventFileEdit
	// EventNotice is something the run reported about itself that is neither
	// output nor a tool call: a denied permission, most importantly. With
	// --permission-prompts none, a denial is the expected outcome of
	// anything unattended dispatch does not authorise, and a run that
	// quietly did nothing is worse than one that says what it was refused.
	EventNotice
	// EventDone ends a successful run and carries the Result.
	EventDone
	// EventError ends a failed run.
	EventError
)

func (t EventType) String() string {
	switch t {
	case EventOutput:
		return "output"
	case EventToolUse:
		return "tool_use"
	case EventFileEdit:
		return "file_edit"
	case EventNotice:
		return "notice"
	case EventDone:
		return "done"
	case EventError:
		return "error"
	default:
		return fmt.Sprintf("event(%d)", int(t))
	}
}

// Event is one item on an executor's stream. A stream ends with exactly one
// EventDone or one EventError, and never both.
type Event struct {
	Type EventType
	// Text is assistant output, a tool's summary, or a notice.
	Text string
	// Tool is the tool's name on EventToolUse and EventFileEdit.
	Tool string
	// Path is the file on EventFileEdit, as the agent named it.
	Path string
	// Result is populated on EventDone.
	Result *Result
	// Err is populated on EventError.
	Err error
}

// Result is what one completed run produced.
//
// FilesChanged is assembled from the file-editing tool calls seen on the
// stream, not from git. It is what the *agent* says it touched; the diff is
// what the working tree says, and the two are worth comparing. Apex never
// marks an item done from either (DESIGN.md §14) — that is the user's
// judgment after reading the diff.
type Result struct {
	SessionID    string
	Model        string
	Usage        provider.Usage
	Turns        int
	CostUSD      float64
	FilesChanged []string
	Duration     time.Duration
	// Summary is the agent's own closing message.
	Summary string
	// LogPath is where the run was teed, for the message that follows it.
	LogPath string
}

// Executor is a builder-loop dispatch target.
type Executor interface {
	Name() string

	// Available reports whether this executor can actually run on this
	// machine. It is checked before every dispatch and by `apex doctor`.
	//
	// DESIGN.md §9 calls this load-bearing rather than decoration: Apex must
	// never assume a binary is present. On failure the error names exactly
	// what is missing.
	Available() error

	// Run dispatches the brief and returns a channel closed exactly once,
	// when the run completes or fails.
	//
	// Cancelling ctx kills the agent and everything it started, and the
	// channel still closes. A caller that abandons the channel must cancel
	// ctx.
	Run(ctx context.Context, brief TaskBrief) (<-chan Event, error)
}

// UnavailableError reports an executor that cannot run here.
//
// It is user-fixable by construction: every way an executor can be
// unavailable — a binary that is not installed, a path that is configured
// wrongly — is something the user changes in their environment.
type UnavailableError struct {
	Executor string
	Reason   string
	Fix      string
	Err      error
}

func (e *UnavailableError) Error() string {
	msg := fmt.Sprintf("executor %s is not available: %s", e.Executor, e.Reason)
	if e.Fix != "" {
		msg += "\n  " + strings.ReplaceAll(e.Fix, "\n", "\n  ")
	}
	return msg
}

func (e *UnavailableError) Unwrap() error { return e.Err }

// UserFixable marks an unavailable executor as an environment problem.
func (e *UnavailableError) UserFixable() bool { return true }

// Emit sends an event unless ctx is done, and reports whether it landed. A
// plain send would park forever if the consumer walked away, which is the
// goroutine leak the interface promises not to have.
func Emit(ctx context.Context, ch chan<- Event, ev Event) bool {
	select {
	case ch <- ev:
		return true
	case <-ctx.Done():
		return false
	}
}

// EmitFinal sends a terminal event — EventDone or EventError.
//
// It differs from Emit in the case that matters: when the run ended *because*
// ctx was cancelled, ctx.Done() is already closed, so Emit would drop the
// error and the consumer would see the channel close with no explanation. A
// consumer still reading deserves to be told why the run stopped.
func EmitFinal(ctx context.Context, ch chan<- Event, ev Event) bool {
	select {
	case ch <- ev:
		return true
	default:
	}
	return Emit(ctx, ch, ev)
}
