package contextfs

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// roundTripFixtures is the property the whole package exists to guarantee:
// parse then render must reproduce the input byte for byte, whatever the user
// put in the file. `apex sync` rewrites a file somebody maintains by hand, so
// anything less than exact is data loss.
var roundTripFixtures = []struct {
	name string
	body string
}{
	{name: "empty", body: ""},
	{name: "only a newline", body: "\n"},
	{name: "no trailing newline", body: "# Projects\n\n## Apex\npath: ~/dev/apex\nA hub."},
	{
		name: "canonical",
		body: "# Projects\n" +
			"<!-- Summary lines are generated by `apex sync`. -->\n" +
			"\n" +
			"## ScholarRAG\n" +
			"path: ~/Development/ScholarRAG\n" +
			"Retrieval over academic papers.\n" +
			"\n" +
			"## Apex\n" +
			"path: ~/Development/Apex\n" +
			"Personal project hub.\n",
	},
	{
		name: "crlf throughout",
		body: "# Projects\r\n\r\n## Apex\r\npath: ~/dev/apex\r\nA hub.\r\n",
	},
	{
		name: "mixed line endings",
		body: "# Projects\n\r\n## Apex\r\npath: ~/dev/apex\nA hub.\r\n\n## Other\npath: ~/dev/other\n",
	},
	{
		name: "blank line runs and trailing whitespace",
		body: "# Projects\n\n\n\n## Apex   \npath:   ~/dev/apex   \nA hub.  \n\n\n\n",
	},
	{
		name: "prose and comments between entries",
		body: "# Projects\n\n" +
			"Some notes I keep at the top of this file.\n\n" +
			"## Apex\npath: ~/dev/apex\nA hub.\n\n" +
			"I should really finish the executor.\n" +
			"<!-- and register ScholarRAG -->\n\n" +
			"## Other\npath: ~/dev/other\n\n" +
			"Trailing prose at the very end.\n",
	},
	{
		name: "unusual ordering and deeper headings",
		body: "## Apex\npath: ~/dev/apex\nA hub.\n\n" +
			"# Projects\n\n" +
			"### A sub-heading that is not an entry\npath: ~/nope\n\n" +
			"## Other\nsome prose first\npath: ~/dev/other\nsummary here\n",
	},
	{
		name: "fenced code containing a heading",
		body: "# Projects\n\n```markdown\n## NotAnEntry\npath: ~/nope\n```\n\n" +
			"## Apex\npath: ~/dev/apex\nA hub.\n",
	},
	{
		name: "malformed entries",
		body: "# Projects\n\n" +
			"## NoPath\nI forgot the path line.\n\n" +
			"## EmptyPath\npath:\n\n" +
			"## Apex\npath: ~/dev/apex\nA hub.\n\n" +
			"## apex\npath: ~/dev/apex-duplicate\n",
	},
	{
		name: "multi-line prose under path",
		body: "## Apex\npath: ~/dev/apex\nThis note spans\ntwo whole lines.\n",
	},
	{
		name: "list under path",
		body: "## Apex\npath: ~/dev/apex\n- a bullet, not a summary\n",
	},
	{
		name: "marked summaries",
		body: "# Projects\n\n## ScholarRAG\npath: ~/dev/ScholarRAG\n<!--apex-->Retrieval over papers. · active\n\n" +
			"## Apex\npath: ~/dev/apex\n<!--apex-->A hub. · active · go\n",
	},
	{
		name: "marker away from the path line, with prose between",
		body: "## Apex\npath: ~/dev/apex\n\nMy own notes first.\n\n<!--apex-->Generated, lower down.\n\n## Other\npath: ~/dev/other\n",
	},
	{
		name: "marked and unmarked lines side by side",
		body: "## Apex\npath: ~/dev/apex\nAn unmarked line I wrote.\n<!--apex-->The generated one.\n",
	},
	{
		name: "marker inside a fenced block",
		body: "## Apex\npath: ~/dev/apex\n\n```\n<!--apex-->documentation, not data\n```\n",
	},
	{name: "no entries at all", body: "Just some markdown with no headings.\n"},
	{name: "unicode", body: "# Projekte\n\n## Über\npath: ~/dev/über\nEin Überblick — ja.\n"},
}

func TestRegistryRoundTripIsByteIdentical(t *testing.T) {
	for _, tt := range roundTripFixtures {
		t.Run(tt.name, func(t *testing.T) {
			in := []byte(tt.body)
			r := ParseRegistry(in, "PROJECTS.md")
			if got := r.Bytes(); !bytes.Equal(got, in) {
				t.Errorf("round trip changed the file\n got: %q\nwant: %q", got, in)
			}
			if r.Changed() {
				t.Error("Changed() is true after a parse with no edits")
			}
			// Re-parsing the rendered bytes must be a fixed point too.
			again := ParseRegistry(r.Bytes(), "PROJECTS.md")
			if got := again.Bytes(); !bytes.Equal(got, in) {
				t.Errorf("second round trip changed the file\n got: %q\nwant: %q", got, in)
			}
		})
	}
}

// TestRegistrySetSummaryIsSurgical checks the other half of the guarantee: a
// rewrite touches the marked summary line and nothing else. Only a marked line
// is Apex's; an unmarked one is the user's prose and is never adopted.
func TestRegistrySetSummaryIsSurgical(t *testing.T) {
	tests := []struct {
		name    string
		body    string
		entry   string
		summary string
		want    string
	}{
		{
			name:    "replaces a marked summary in place",
			body:    "# Projects\n\n## Apex\npath: ~/dev/apex\n<!--apex-->Old summary.\n\n## Other\npath: ~/dev/other\n<!--apex-->Untouched.\n",
			entry:   "Apex",
			summary: "New summary.",
			want:    "# Projects\n\n## Apex\npath: ~/dev/apex\n<!--apex-->New summary.\n\n## Other\npath: ~/dev/other\n<!--apex-->Untouched.\n",
		},
		{
			name:    "replaces a marked line wherever it sits in the entry",
			body:    "## Apex\npath: ~/dev/apex\n\nSome prose I wrote.\n\n<!--apex-->Old.\n\n## Other\npath: ~/dev/other\n",
			entry:   "Apex",
			summary: "New.",
			want:    "## Apex\npath: ~/dev/apex\n\nSome prose I wrote.\n\n<!--apex-->New.\n\n## Other\npath: ~/dev/other\n",
		},
		{
			name:    "inserts when the entry has no summary at all",
			body:    "## Apex\npath: ~/dev/apex\n\n## Other\npath: ~/dev/other\n",
			entry:   "Apex",
			summary: "Fresh.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->Fresh.\n\n## Other\npath: ~/dev/other\n",
		},
		{
			name:    "never adopts an unmarked line, however summary-shaped",
			body:    "## Apex\npath: ~/dev/apex\nA line I wrote before markers existed.\n",
			entry:   "Apex",
			summary: "Generated.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->Generated.\n\nA line I wrote before markers existed.\n",
		},
		{
			name:    "keeps CRLF terminators when replacing",
			body:    "## Apex\r\npath: ~/dev/apex\r\n<!--apex-->Old.\r\n",
			entry:   "Apex",
			summary: "New.",
			want:    "## Apex\r\npath: ~/dev/apex\r\n<!--apex-->New.\r\n",
		},
		{
			name:    "inserts with the file's CRLF terminator",
			body:    "## Apex\r\npath: ~/dev/apex\r\n",
			entry:   "Apex",
			summary: "New.",
			want:    "## Apex\r\npath: ~/dev/apex\r\n<!--apex-->New.\r\n",
		},
		{
			name:    "does not overwrite a multi-line paragraph",
			body:    "## Apex\npath: ~/dev/apex\nThis note spans\ntwo whole lines.\n",
			entry:   "Apex",
			summary: "Generated.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->Generated.\n\nThis note spans\ntwo whole lines.\n",
		},
		{
			name:    "does not overwrite a list",
			body:    "## Apex\npath: ~/dev/apex\n- a bullet\n- another\n",
			entry:   "Apex",
			summary: "Generated.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->Generated.\n\n- a bullet\n- another\n",
		},
		{
			name:    "does not overwrite an unrelated comment",
			body:    "## Apex\npath: ~/dev/apex\n<!-- a note to self -->\n",
			entry:   "Apex",
			summary: "Generated.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->Generated.\n\n<!-- a note to self -->\n",
		},
		{
			name:    "matches the entry name case-insensitively",
			body:    "## Apex\npath: ~/dev/apex\n<!--apex-->Old.\n",
			entry:   "APEX",
			summary: "New.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->New.\n",
		},
		{
			name:    "folds a multi-line summary onto one line",
			body:    "## Apex\npath: ~/dev/apex\n<!--apex-->Old.\n",
			entry:   "Apex",
			summary: "Line one\nline two\n\nline three",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->Line one line two line three\n",
		},
		{
			name:    "strips markers that would change how the file parses",
			body:    "## Apex\npath: ~/dev/apex\n<!--apex-->Old.\n",
			entry:   "Apex",
			summary: "## not a heading",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->not a heading\n",
		},
		{
			name:    "strips an embedded marker rather than doubling it",
			body:    "## Apex\npath: ~/dev/apex\n<!--apex-->Old.\n",
			entry:   "Apex",
			summary: "before <!--apex--> after",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->before after\n",
		},
		{
			name:    "an empty summary leaves the entry alone",
			body:    "## Apex\npath: ~/dev/apex\nHand written.\n",
			entry:   "Apex",
			summary: "   ",
			want:    "## Apex\npath: ~/dev/apex\nHand written.\n",
		},
		{
			name:    "terminates a file that ended without a newline",
			body:    "## Apex\npath: ~/dev/apex",
			entry:   "Apex",
			summary: "New.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->New.\n",
		},
		{
			name:    "a malformed entry elsewhere is left in the file",
			body:    "## NoPath\nnothing here\n\n## Apex\npath: ~/dev/apex\n<!--apex-->Old.\n",
			entry:   "Apex",
			summary: "New.",
			want:    "## NoPath\nnothing here\n\n## Apex\npath: ~/dev/apex\n<!--apex-->New.\n",
		},
		{
			name:    "a marker inside a fenced block is not the summary",
			body:    "## Apex\npath: ~/dev/apex\n\n```\n<!--apex-->documentation, not data\n```\n",
			entry:   "Apex",
			summary: "New.",
			want:    "## Apex\npath: ~/dev/apex\n<!--apex-->New.\n\n```\n<!--apex-->documentation, not data\n```\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			r := ParseRegistry([]byte(tt.body), "PROJECTS.md")
			if err := r.SetSummary(tt.entry, tt.summary); err != nil {
				t.Fatalf("SetSummary: %v", err)
			}
			if got := string(r.Bytes()); got != tt.want {
				t.Errorf("SetSummary produced\n %q\nwant\n %q", got, tt.want)
			}
		})
	}
}

// TestRegistrySetSummaryConverges is what makes the insert-a-line behaviour
// safe: the second sync must rewrite the marked line the first inserted, not
// insert another, and the user's prose must survive every round.
func TestRegistrySetSummaryConverges(t *testing.T) {
	for _, body := range []string{
		"## Apex\npath: ~/dev/apex\nUser prose that\nspans two lines.\n",
		"## Apex\npath: ~/dev/apex\nAn unmarked line from before markers existed.\n",
		"## Apex\npath: ~/dev/apex\n",
	} {
		t.Run(body, func(t *testing.T) {
			r := ParseRegistry([]byte(body), "PROJECTS.md")
			if err := r.SetSummary("Apex", "First."); err != nil {
				t.Fatalf("first SetSummary: %v", err)
			}
			first := r.Bytes()
			if n := strings.Count(string(first), SummaryMarker); n != 1 {
				t.Fatalf("first sync wrote %d markers, want 1: %q", n, first)
			}

			r = ParseRegistry(first, "PROJECTS.md")
			if err := r.SetSummary("Apex", "Second."); err != nil {
				t.Fatalf("second SetSummary: %v", err)
			}
			second := string(r.Bytes())
			if n := strings.Count(second, SummaryMarker); n != 1 {
				t.Errorf("second sync wrote %d markers, want 1: %q", n, second)
			}
			if !strings.Contains(second, SummaryMarker+"Second.") {
				t.Errorf("second sync did not rewrite the marked line: %q", second)
			}
			if strings.Contains(second, "First.") {
				t.Errorf("the first summary survived into the second sync: %q", second)
			}
			// Every line of the original file is still there.
			for _, line := range strings.Split(strings.TrimSuffix(body, "\n"), "\n") {
				if !strings.Contains(second, line) {
					t.Errorf("sync lost the line %q: %q", line, second)
				}
			}

			// And a third must be a no-op for the same summary.
			r = ParseRegistry([]byte(second), "PROJECTS.md")
			if err := r.SetSummary("Apex", "Second."); err != nil {
				t.Fatalf("third SetSummary: %v", err)
			}
			if r.Changed() {
				t.Errorf("rewriting the same summary changed the file: %q", r.Bytes())
			}
		})
	}
}

func TestRegistryParsing(t *testing.T) {
	body := "# Projects\n" +
		"<!-- generated summaries below -->\n" +
		"\n" +
		"## ScholarRAG\n" +
		"path: ~/Development/ScholarRAG\n" +
		"Retrieval over academic papers.\n" +
		"\n" +
		"## NoPath\n" +
		"I forgot to say where it lives.\n" +
		"\n" +
		"## EmptyPath\n" +
		"path:   \n" +
		"\n" +
		"## Apex\n" +
		"Some prose that comes before the path line.\n" +
		"PATH: ~/Development/Apex\n" +
		"\n" +
		"## apex\n" +
		"path: ~/elsewhere\n"

	r := ParseRegistry([]byte(body), "PROJECTS.md")

	entries := r.Entries()
	if len(entries) != 2 {
		t.Fatalf("parsed %d entries, want 2: %+v", len(entries), entries)
	}
	if entries[0].Name != "ScholarRAG" || entries[0].Path != "~/Development/ScholarRAG" {
		t.Errorf("entry 0 = %+v", entries[0])
	}
	if entries[0].Summary != "Retrieval over academic papers." {
		t.Errorf("entry 0 summary = %q", entries[0].Summary)
	}
	if !entries[0].HasSummary() {
		t.Error("entry 0 should have a summary slot")
	}
	if entries[1].Name != "Apex" || entries[1].Path != "~/Development/Apex" {
		t.Errorf("entry 1 = %+v", entries[1])
	}
	if entries[1].HasSummary() {
		t.Error("entry 1 has no line under path:, so it should have no slot")
	}
	if entries[0].Line != 4 {
		t.Errorf("entry 0 heading line = %d, want 4", entries[0].Line)
	}

	problems := r.Problems()
	if len(problems) != 3 {
		t.Fatalf("got %d problems, want 3: %+v", len(problems), problems)
	}
	joined := strings.ToLower(problems[0].String() + problems[1].String() + problems[2].String())
	for _, want := range []string{"nopath", "emptypath", "duplicate"} {
		if !strings.Contains(joined, want) {
			t.Errorf("problems do not mention %q: %v", want, problems)
		}
	}

	if _, ok := r.Lookup("scholarrag"); !ok {
		t.Error("Lookup is not case-insensitive")
	}
	if _, ok := r.Lookup("nothing"); ok {
		t.Error("Lookup found an entry that is not there")
	}
}

// TestRegistryMarkerIsAuthoritative covers the reading half of the marker rule:
// a marked line wins wherever it sits, and an unmarked line is still reported
// (so an entry written before markers existed is not shown as blank) but is
// flagged as not Apex's to rewrite.
func TestRegistryMarkerIsAuthoritative(t *testing.T) {
	tests := []struct {
		name        string
		body        string
		wantSummary string
		wantMarked  bool
		wantAny     bool
	}{
		{
			name:        "marked line under path",
			body:        "## Apex\npath: ~/dev/apex\n<!--apex-->Generated text.\n",
			wantSummary: "Generated text.",
			wantMarked:  true,
			wantAny:     true,
		},
		{
			name:        "marked line lower down wins over the positional one",
			body:        "## Apex\npath: ~/dev/apex\nAn unmarked line.\n\n<!--apex-->The real summary.\n",
			wantSummary: "The real summary.",
			wantMarked:  true,
			wantAny:     true,
		},
		{
			name:        "marker above the path line still counts",
			body:        "## Apex\n<!--apex-->Above the path.\npath: ~/dev/apex\n",
			wantSummary: "Above the path.",
			wantMarked:  true,
			wantAny:     true,
		},
		{
			name:        "the first marker wins when there are two",
			body:        "## Apex\npath: ~/dev/apex\n<!--apex-->First.\n<!--apex-->Second.\n",
			wantSummary: "First.",
			wantMarked:  true,
			wantAny:     true,
		},
		{
			name:        "marker with surrounding whitespace",
			body:        "## Apex\npath: ~/dev/apex\n  <!--apex-->   Padded.  \n",
			wantSummary: "Padded.",
			wantMarked:  true,
			wantAny:     true,
		},
		{
			name:        "unmarked positional fallback is read but not owned",
			body:        "## Apex\npath: ~/dev/apex\nWritten before markers existed.\n",
			wantSummary: "Written before markers existed.",
			wantMarked:  false,
			wantAny:     true,
		},
		{
			name:    "a marker inside a fence is not a summary",
			body:    "## Apex\npath: ~/dev/apex\n\n```\n<!--apex-->not data\n```\n",
			wantAny: false,
		},
		{
			name:    "a multi-line paragraph is not a summary",
			body:    "## Apex\npath: ~/dev/apex\nTwo lines\nof prose.\n",
			wantAny: false,
		},
		{
			name:    "no summary at all",
			body:    "## Apex\npath: ~/dev/apex\n",
			wantAny: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			r := ParseRegistry([]byte(tt.body), "PROJECTS.md")
			entries := r.Entries()
			if len(entries) != 1 {
				t.Fatalf("parsed %d entries, want 1: %+v", len(entries), entries)
			}
			e := entries[0]
			if e.HasSummary() != tt.wantAny {
				t.Errorf("HasSummary = %v, want %v", e.HasSummary(), tt.wantAny)
			}
			if e.Marked != tt.wantMarked {
				t.Errorf("Marked = %v, want %v", e.Marked, tt.wantMarked)
			}
			if e.Summary != tt.wantSummary {
				t.Errorf("Summary = %q, want %q", e.Summary, tt.wantSummary)
			}
		})
	}
}

func TestRegistrySetSummaryUnknownEntry(t *testing.T) {
	r := ParseRegistry([]byte("## Apex\npath: ~/dev/apex\n"), "PROJECTS.md")
	err := r.SetSummary("Nope", "x")
	var unknown *UnknownEntryError
	if !errors.As(err, &unknown) {
		t.Fatalf("err = %v, want *UnknownEntryError", err)
	}
	if !unknown.UserFixable() {
		t.Error("an unknown entry should be user-fixable")
	}
}

func TestLoadRegistryAbsent(t *testing.T) {
	path := filepath.Join(t.TempDir(), "context", ProjectsFile)
	r, err := LoadRegistry(context.Background(), path)
	if err != nil {
		t.Fatalf("LoadRegistry: %v", err)
	}
	if r.Present {
		t.Error("Present is true for a file that does not exist")
	}
	if len(r.Entries()) != 0 {
		t.Errorf("absent registry has entries: %+v", r.Entries())
	}
}

func TestRegistrySaveIsAtomicAndSurgical(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	path := filepath.Join(dir, ProjectsFile)

	body := "# Projects\n\n## Apex\npath: ~/dev/apex\n<!--apex-->Old.\n\n## Other\npath: ~/dev/other\nKeep me.\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	r, err := LoadRegistry(ctx, path)
	if err != nil {
		t.Fatalf("LoadRegistry: %v", err)
	}
	if !r.Present {
		t.Fatal("Present is false for a file that exists")
	}

	// Saving an unchanged registry must not rewrite the file at all.
	if err := r.Save(ctx); err != nil {
		t.Fatalf("Save (unchanged): %v", err)
	}
	if got, _ := os.ReadFile(path); string(got) != body {
		t.Errorf("no-op Save changed the file: %q", got)
	}

	if err := r.SetSummary("Apex", "New."); err != nil {
		t.Fatalf("SetSummary: %v", err)
	}
	if err := r.Save(ctx); err != nil {
		t.Fatalf("Save: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# Projects\n\n## Apex\npath: ~/dev/apex\n<!--apex-->New.\n\n## Other\npath: ~/dev/other\nKeep me.\n"
	if string(got) != want {
		t.Errorf("saved file =\n %q\nwant\n %q", got, want)
	}

	// The temp file used for the atomic rename must be gone.
	names, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(names) != 1 || names[0].Name() != ProjectsFile {
		var got []string
		for _, n := range names {
			got = append(got, n.Name())
		}
		t.Errorf("directory contains %v, want only %s", got, ProjectsFile)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Errorf("mode = %o, want 600 (the mode the file already had)", perm)
	}
}

// TestRegistryHeadingsRoundTrip: Apex appends entries to this file, so a name
// it writes has to be the name it reads back. A closing run of '#' is stripped
// only after a space, as CommonMark has it, so "C#" names C#.
func TestRegistryHeadingsRoundTrip(t *testing.T) {
	tests := map[string]string{
		"## C#\npath: ~/c\n":        "C#",
		"## C# ##\npath: ~/c\n":     "C#",
		"## Atlas ##\npath: ~/a\n":  "Atlas",
		"## Atlas\t#\npath: ~/a\n":  "Atlas",
		"## F# Tools\npath: ~/f\n":  "F# Tools",
		"## Plain\npath: ~/plain\n": "Plain",
	}
	for body, want := range tests {
		entries := ParseRegistry([]byte(body), "PROJECTS.md").Entries()
		if len(entries) != 1 || entries[0].Name != want {
			t.Errorf("%q parsed as %+v, want one entry named %q", body, entries, want)
		}
	}
}

// TestRegistryAddEntryReadsBack: an entry Apex appends is one it can find
// again, and a name that could not be is refused with the file untouched.
func TestRegistryAddEntryReadsBack(t *testing.T) {
	body := "# Projects\n\n## Atlas\npath: ~/Development/Atlas\n"
	r := ParseRegistry([]byte(body), "PROJECTS.md")

	if err := r.AddEntry("C#", "~/Development/C#"); err != nil {
		t.Fatalf("AddEntry: %v", err)
	}
	if e, ok := r.Lookup("C#"); !ok || e.Path != "~/Development/C#" {
		t.Errorf("the appended entry does not read back: %+v, %v", e, ok)
	}

	for _, name := range []string{"two\nlines", "###"} {
		before := string(r.Bytes())
		if err := r.AddEntry(name, "~/Development/x"); err == nil {
			t.Errorf("AddEntry(%q) succeeded; it cannot be read back as written", name)
		}
		if after := string(r.Bytes()); after != before {
			t.Errorf("a refused AddEntry(%q) still changed the file:\n%s", name, after)
		}
	}
	if len(r.Problems()) != 0 {
		t.Errorf("appending left problems behind: %v", r.Problems())
	}
}
