package contextfs

import (
	"bytes"
	"context"
	"fmt"
	"strings"
)

// The registry format (DESIGN.md §6):
//
//	# Projects
//	<!-- Summary lines are generated by `apex sync`. Edit PROJECT.md instead. -->
//
//	## ScholarRAG
//	path: ~/Development/ScholarRAG
//	<!--apex-->Retrieval over academic papers. Active; blocked on chunking.
//
// An entry is a level-2 heading, a `path:` line somewhere before the next
// heading, and an optional generated summary line.
//
// A generated summary carries an explicit marker, and only a marked line is
// ever Apex's to rewrite. Identifying it positionally works, but a hand-edit
// that shifts a line by one would then be silently destructive; a marker makes
// the round trip safe by construction.
//
//	If the entry has a marked line, that line is the summary. It is
//	authoritative wherever it sits in the entry, and it is rewritten in place.
//
//	If it has none, SetSummary INSERTS a marked line under `path:`. It never
//	adopts an unmarked line, because an unmarked line is the user's prose.
//
// A positional fallback survives for reading only, so an entry written before
// markers existed still reports its current summary: an unmarked single line
// directly under `path:`, when the line after THAT is blank, a heading, or end
// of file. Everything else — a paragraph, a list, a comment, prose after a
// blank line — is reported as no summary at all.
//
// An insertion leaves a blank line behind it when the next line is prose, so
// the next parse finds a well-formed marked line and rewrites it in place.
// Repeated syncs therefore converge instead of accreting lines.

// SummaryMarker prefixes every summary line `apex sync` generates. It is an
// HTML comment, so it renders as nothing in any markdown viewer while staying
// plainly visible in the file the user edits.
const SummaryMarker = "<!--apex-->"

// Entry is one parsed registry entry.
type Entry struct {
	// Name is the level-2 heading text.
	Name string
	// Path is the value of the entry's `path:` line, exactly as written.
	Path string
	// Summary is the summary line's text, with any marker stripped, or ""
	// when the entry has no summary line at all.
	Summary string
	// Marked reports whether the summary line carries SummaryMarker. Only a
	// marked line is Apex's to rewrite; an unmarked one is read and reported
	// but never overwritten.
	Marked bool
	// Line is the 1-based line number of the heading, for error messages.
	Line int

	// heading, pathLine and summaryLine index Registry.lines. summaryLine is
	// -1 when the entry has no summary line.
	heading     int
	pathLine    int
	summaryLine int
}

// HasSummary reports whether the entry currently carries a summary line, marked
// or not.
func (e Entry) HasSummary() bool { return e.summaryLine >= 0 }

// Problem is a registry entry Apex could not parse. It is reported to the user
// and skipped; its lines survive any rewrite verbatim, because dropping a badly
// formed entry from a file the user maintains by hand would lose their work.
type Problem struct {
	// Line is the 1-based line of the heading the problem belongs to.
	Line int
	// Name is the heading text, when the entry had one.
	Name string
	// Msg says what is wrong, in terms of what to edit.
	Msg string
}

func (p Problem) String() string {
	if p.Name != "" {
		return fmt.Sprintf("line %d: %s: %s", p.Line, p.Name, p.Msg)
	}
	return fmt.Sprintf("line %d: %s", p.Line, p.Msg)
}

// Registry is a parsed PROJECTS.md that remembers its exact bytes. Bytes
// returns the input unchanged until SetSummary is called, and SetSummary
// rewrites only the summary slot of the entry it names.
type Registry struct {
	// Path is the file this registry was loaded from.
	Path string
	// Present is false when PROJECTS.md does not exist. An absent registry is
	// an empty one, not an error.
	Present bool

	original []byte
	lines    []string
	entries  []Entry
	problems []Problem
}

// LoadRegistry reads and parses PROJECTS.md. A file that does not exist yields
// an empty Registry with Present false and no error.
func LoadRegistry(ctx context.Context, path string) (*Registry, error) {
	doc, err := LoadDocument(ctx, path)
	if err != nil {
		return nil, err
	}
	if !doc.Present {
		return &Registry{Path: path}, nil
	}
	r := ParseRegistry([]byte(doc.Body), path)
	r.Present = true
	return r, nil
}

// ParseRegistry parses registry bytes that are already in hand.
//
// Parsing never fails: a heading Apex cannot make sense of becomes a Problem,
// so the caller can report every bad entry at once rather than aborting on the
// first one.
func ParseRegistry(data []byte, path string) *Registry {
	r := &Registry{
		Path:     path,
		Present:  true,
		original: append([]byte(nil), data...),
		lines:    splitLines(data),
	}
	r.parse()
	return r
}

// Entries returns the entries Apex was able to parse, in file order.
func (r *Registry) Entries() []Entry {
	out := make([]Entry, len(r.entries))
	copy(out, r.entries)
	return out
}

// Problems returns the entries that could not be parsed.
func (r *Registry) Problems() []Problem {
	out := make([]Problem, len(r.problems))
	copy(out, r.problems)
	return out
}

// Lookup returns the entry with the given name, matched case-insensitively.
func (r *Registry) Lookup(name string) (Entry, bool) {
	for _, e := range r.entries {
		if strings.EqualFold(e.Name, name) {
			return e, true
		}
	}
	return Entry{}, false
}

// Bytes renders the registry. Parsing and rendering with no intervening
// SetSummary is byte-identical to the input, including comments, blank line
// runs, CRLF terminators, and a missing final newline.
func (r *Registry) Bytes() []byte { return joinLines(r.lines) }

// Changed reports whether the registry differs from the bytes it was parsed
// from, so a sync that regenerated nothing does not rewrite the file at all.
func (r *Registry) Changed() bool { return !bytes.Equal(r.original, r.Bytes()) }

// Save writes the registry back atomically, and does nothing when nothing
// changed.
func (r *Registry) Save(ctx context.Context) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if r.Path == "" {
		return fmt.Errorf("registry: no path recorded")
	}
	if r.Present && !r.Changed() {
		return nil
	}
	data := r.Bytes()
	if err := writeAtomic(r.Path, data); err != nil {
		return fmt.Errorf("write registry: %w", err)
	}
	r.original = append([]byte(nil), data...)
	r.Present = true
	return nil
}

// UnknownEntryError is returned by SetSummary for a name that is not in the
// registry.
type UnknownEntryError struct{ Name string }

func (e *UnknownEntryError) Error() string {
	return fmt.Sprintf("no registry entry named %q", e.Name)
}

// UserFixable marks an unknown entry as something the user names, not a bug.
func (e *UnknownEntryError) UserFixable() bool { return true }

// SetSummary replaces the generated summary line of one entry, matched by name
// case-insensitively. Nothing else in the file is touched. An empty summary is
// ignored rather than blanking the line, since a generator with nothing to say
// must not erase what is already there.
func (r *Registry) SetSummary(name, summary string) error {
	idx := -1
	for i, e := range r.entries {
		if strings.EqualFold(e.Name, name) {
			idx = i
			break
		}
	}
	if idx < 0 {
		return &UnknownEntryError{Name: name}
	}

	summary = sanitizeSummary(summary)
	if summary == "" {
		return nil
	}

	e := r.entries[idx]
	marked := SummaryMarker + summary

	if e.Marked {
		if lineText(r.lines[e.summaryLine]) == marked {
			return nil
		}
		ending := lineEnding(r.lines[e.summaryLine])
		if ending == "" {
			ending = r.defaultEnding()
		}
		r.lines[e.summaryLine] = marked + ending
		r.parse()
		return nil
	}

	// No marked line: insert one under `path:`. An unmarked line already
	// there is the user's prose and is left where it is, not adopted.
	ending := lineEnding(r.lines[e.pathLine])
	if ending == "" {
		// The path line ended the file without a newline. Terminate it so
		// the inserted summary is a line of its own.
		ending = r.defaultEnding()
		r.lines[e.pathLine] += ending
	}
	inserted := []string{marked + ending}
	if next := e.pathLine + 1; next < len(r.lines) {
		nextText := strings.TrimSpace(lineText(r.lines[next]))
		if nextText != "" && !strings.HasPrefix(nextText, "#") {
			inserted = append(inserted, ending)
		}
	}
	r.lines = append(r.lines[:e.pathLine+1],
		append(inserted, r.lines[e.pathLine+1:]...)...)
	r.parse()
	return nil
}

// defaultEnding is the terminator used for inserted lines: whatever the file
// already uses, so a CRLF registry stays CRLF.
func (r *Registry) defaultEnding() string {
	for _, l := range r.lines {
		if e := lineEnding(l); e != "" {
			return e
		}
	}
	return "\n"
}

// sanitizeSummary folds a generated summary into the single line of prose the
// format expects, and strips anything that would change how the file parses on
// the next sync: embedded markers, and leading markdown markers that would turn
// the line into a heading, a list item, or another `path:` line.
func sanitizeSummary(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	// A marker inside the text would produce two on one line, and the second
	// would survive into the next parse as part of the summary.
	s = strings.ReplaceAll(s, SummaryMarker, "")
	s = strings.Join(strings.Fields(s), " ")
	for {
		trimmed := strings.TrimLeft(s, "#-*+>| \t")
		if trimmed == s {
			break
		}
		s = trimmed
	}
	if _, isPath := parsePathLine(s); isPath {
		return ""
	}
	return s
}

// --- parsing ----------------------------------------------------------------

// parse rebuilds entries and problems from lines. It runs again after every
// mutation, because inserting a line shifts every index after it and a stale
// index is how a rewriter corrupts a file.
func (r *Registry) parse() {
	r.entries = nil
	r.problems = nil

	type pending struct {
		name     string
		heading  int
		pathLine int
		path     string
		markLine int // first marked line inside the entry, or -1
	}
	var cur *pending
	inFence := false

	flush := func(end int) {
		if cur == nil {
			return
		}
		defer func() { cur = nil }()

		switch {
		case cur.pathLine < 0:
			r.problems = append(r.problems, Problem{
				Line: cur.heading + 1,
				Name: cur.name,
				Msg:  "no `path:` line before the next heading",
			})
			return
		case cur.path == "":
			r.problems = append(r.problems, Problem{
				Line: cur.pathLine + 1,
				Name: cur.name,
				Msg:  "`path:` line has no value",
			})
			return
		}

		e := Entry{
			Name:        cur.name,
			Path:        cur.path,
			Line:        cur.heading + 1,
			heading:     cur.heading,
			pathLine:    cur.pathLine,
			summaryLine: -1,
		}
		switch {
		case cur.markLine >= 0:
			// A marker is authoritative wherever it sits in the entry.
			e.summaryLine = cur.markLine
			e.Marked = true
			e.Summary = markedSummary(lineText(r.lines[cur.markLine]))
		default:
			// Fallback, for reading only: an entry written before markers
			// existed still reports the summary it has.
			if slot := summarySlot(r.lines, cur.pathLine, end); slot >= 0 {
				e.summaryLine = slot
				e.Summary = strings.TrimSpace(lineText(r.lines[slot]))
			}
		}
		r.entries = append(r.entries, e)
	}

	for i, raw := range r.lines {
		text := lineText(raw)
		if isFence(text) {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}
		if name, ok := parseHeading(text); ok {
			flush(i)
			cur = &pending{name: name, heading: i, pathLine: -1, markLine: -1}
			continue
		}
		if cur == nil {
			continue
		}
		if cur.pathLine < 0 {
			if value, ok := parsePathLine(text); ok {
				cur.pathLine = i
				cur.path = value
				continue
			}
		}
		if cur.markLine < 0 && isMarkedLine(text) {
			cur.markLine = i
		}
	}
	flush(len(r.lines))

	r.reportDuplicates()
}

// reportDuplicates demotes every repeat of a name to a problem. Two entries
// with one name would resolve to one registry row, so the later ones are
// skipped — but their lines stay in the file.
func (r *Registry) reportDuplicates() {
	seen := map[string]int{}
	kept := r.entries[:0]
	for _, e := range r.entries {
		key := strings.ToLower(e.Name)
		if first, dup := seen[key]; dup {
			r.problems = append(r.problems, Problem{
				Line: e.Line,
				Name: e.Name,
				Msg:  fmt.Sprintf("duplicate of the entry on line %d", first),
			})
			continue
		}
		seen[key] = e.Line
		kept = append(kept, e)
	}
	r.entries = kept
}

// parseHeading matches a level-2 heading, which is what starts an entry. A
// level-1 heading is the file title and a level-3 heading is structure inside
// somebody's notes; neither is an entry.
func parseHeading(text string) (string, bool) {
	if !strings.HasPrefix(text, "##") {
		return "", false
	}
	rest := text[2:]
	if strings.HasPrefix(rest, "#") {
		return "", false
	}
	if rest != "" && rest[0] != ' ' && rest[0] != '\t' {
		return "", false
	}
	// A trailing run of '#' is the closed-ATX form.
	name := strings.TrimSpace(strings.TrimRight(strings.TrimSpace(rest), "#"))
	if name == "" {
		return "", false
	}
	return name, true
}

// parsePathLine matches the `path:` line. The key is matched case-insensitively
// because the user types it by hand.
func parsePathLine(text string) (string, bool) {
	trimmed := strings.TrimLeft(text, " \t")
	const key = "path:"
	if len(trimmed) < len(key) || !strings.EqualFold(trimmed[:len(key)], key) {
		return "", false
	}
	return strings.TrimSpace(trimmed[len(key):]), true
}

// isMarkedLine reports whether a line is a generated summary.
func isMarkedLine(text string) bool {
	return strings.HasPrefix(strings.TrimSpace(text), SummaryMarker)
}

// markedSummary returns a marked line's text with the marker removed.
func markedSummary(text string) string {
	return strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(text), SummaryMarker))
}

// isFence reports whether a line opens or closes a fenced code block. Headings
// inside a fence are text, not structure.
func isFence(text string) bool {
	t := strings.TrimSpace(text)
	return strings.HasPrefix(t, "```") || strings.HasPrefix(t, "~~~")
}

// summarySlot returns the index of the line Apex may rewrite for an entry whose
// `path:` line is at pathLine and which ends at end (exclusive), or -1 when the
// entry has no slot. See the rule documented at the top of this file.
func summarySlot(lines []string, pathLine, end int) int {
	i := pathLine + 1
	if i >= end || i >= len(lines) {
		return -1
	}
	text := lineText(lines[i])
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return -1
	}
	// Anything that is structure rather than prose belongs to the user.
	if strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "<!--") ||
		strings.HasPrefix(trimmed, "-") || strings.HasPrefix(trimmed, "*") ||
		strings.HasPrefix(trimmed, "+") || strings.HasPrefix(trimmed, ">") ||
		strings.HasPrefix(trimmed, "|") || isFence(trimmed) {
		return -1
	}
	if _, ok := parsePathLine(text); ok {
		return -1
	}
	// A multi-line block under `path:` is a paragraph the user wrote, not a
	// one-line generated summary. Leave all of it alone.
	if j := i + 1; j < end && j < len(lines) {
		next := strings.TrimSpace(lineText(lines[j]))
		if next != "" && !strings.HasPrefix(next, "#") {
			return -1
		}
	}
	return i
}
